services:
  - type: web
    name: data-janitor-orchestrator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    plan: starter
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
